#!/bin/sh

echo "Running GIT services..."

git status

echo "Enter remote name..."
read REMOTE

echo "Enter commit message..."
read MESSAGE

git add --all
if [ $REMOTE = "" || $MESSAGE = "" ] ; then
	echo "Empty string. Exiting script..."
	exit 0
else
	git commit -m "$MESSAGE"
	git push $REMOTE master
fi